export const DIFFICULTIES = ["easy", "medium", "hard"];

export const EXPERIENCE_TYPES = ["onsite", "online", "phone", "take-home"];

export const RESULTS = ["selected", "rejected", "pending", "no-response"];

export const COMPANIES = [
  "Accenture",
  "Accenture Japan",
  "Adobe",
  "Airbnb",
  "American Express",
  "Amdocs",
  "Apple",
  "Arista Networks",
  "Ashok Leyland",
  "Atlassian",
  "Bajaj Auto",
  "Barclays",
  "BNY Mellon",
  "Bosch",
  "Byju’s",
  "Cadence",
  "Capgemini",
  "Citi",
  "Cisco",
  "Cognizant",
  "CRED",
  "Deutsche Bank",
  "Deloitte",
  "Dream11",
  "EXL Analytics",
  "EY",
  "ExxonMobil",
  "Flipkart",
  "Fractal Analytics",
  "GE",
  "Goldman Sachs",
  "Google",
  "HCL",
  "HDFC Bank",
  "Hero MotoCorp",
  "Honeywell",
  "HSBC",
  "ICICI Bank",
  "IDBI Bank",
  "Infosys",
  "Intel",
  "JPMorgan",
  "JSW",
  "Juniper Networks",
  "KPMG",
  "L&T Technology Services",
  "Larsen & Toubro",
  "LatentView Analytics",
  "Maruti Suzuki",
  "MathWorks",
  "Meesho",
  "Meta",
  "Micron",
  "Microsoft",
  "Morgan Stanley",
  "Mu Sigma",
  "Netflix",
  "NVIDIA",
  "Nomura",
  "Oracle",
  "Oracle Financial Services",
  "Paytm",
  "PhonePe",
  "Publicis Sapient",
  "PwC",
  "Qualcomm",
  "Razorpay",
  "Reliance Industries",
  "Saint Gobain",
  "Salesforce",
  "Samsung Electronics",
  "Samsung Research",
  "Schlumberger",
  "ServiceNow",
  "ShareChat",
  "Shell",
  "Siemens",
  "Standard Chartered",
  "Swiggy",
  "Synopsys",
  "Tata Power",
  "Tata Projects",
  "Tata Steel",
  "TCS",
  "Tech Mahindra",
  "Texas Instruments",
  "Tiger Analytics",
  "Twitter (X)",
  "UBS",
  "Uber",
  "Unacademy",
  "Vedantu",
  "VMware",
  "Wells Fargo",
  "Western Digital",
  "Wipro",
  "ZS Associates",
  "Zomato",
];

export const SORT_OPTIONS = [
  { label: "Latest", value: "latest" },
  { label: "Most Voted", value: "mostVoted" },
  { label: "Most Viewed", value: "mostViewed" },
  { label: "Oldest", value: "oldest" },
];

export const DIFFICULTY_COLORS = {
  easy: "text-emerald-400 bg-emerald-400/10 border-emerald-400/30",
  medium: "text-yellow-400 bg-yellow-400/10 border-yellow-400/30",
  hard: "text-red-400 bg-red-400/10 border-red-400/30",
};

export const RESULT_COLORS = {
  selected: "text-emerald-400 bg-emerald-400/10",
  rejected: "text-red-400 bg-red-400/10",
  pending: "text-yellow-400 bg-yellow-400/10",
  "no-response": "text-slate-400 bg-slate-400/10",
};
